name: get repo url

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: print default branch name
        run: |
          echo "https://github.com/${{github.repository}}"
