name: get default branch name

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: print default branch name
        run: |
          echo "github.event.repository.default_branch"
